# Generated by Django 5.2.1 on 2026-08-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(help_text="Identifiant libre de l'événement à l'origine de la notification.", max_length=100, verbose_name='Événement')),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=20, verbose_name='Niveau')),
                ('message', models.TextField(verbose_name='Message')),
                ('triggered_by_username', models.CharField(blank=True, help_text="Username de l'utilisateur authentifié à l'origine de l'action, si applicable.", max_length=150, verbose_name='Déclenché par')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyée'), ('FAILED', 'Échec')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyée le')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
