# Generated by Django 3.2.2 on 2021-05-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='heating_priority',
            field=models.IntegerField(unique=True),
        ),
    ]
