version: '3.8'

services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
    env_file:
      - .env
    devices:
      - "${SERIAL_PORT}:${SERIAL_PORT}"
    # restart: always

  postgres:
    image: postgres:17.0-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # restart: always

volumes:
  postgres_data:
