# Generated by Django 5.2.1 on 2025-10-10 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actuators', '0001_initial'),
        ('sensors', '0003_rename_nom_temperaturesensor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('heating_control_mode', models.CharField(choices=[('thermostat', 'Piloté par plannings de température'), ('on_off', 'Piloté par plannings on/off')], default='on_off', help_text='Définit si la pièce est pilotée par consigne de température ou en on/off.', max_length=20, verbose_name='Mode de pilotage du chauffage')),
                ('current_setpoint', models.FloatField(blank=True, help_text='Température souhaitée lorsque la pièce est pilotée par thermostat (en C°).', null=True, verbose_name='Consigne de température')),
                ('current_on_off_state', models.CharField(choices=[('off', 'Éteint'), ('on', 'Allumé'), ('unknown', 'Non défini')], default='unknown', help_text='Consigne lorsque la pièce est pilotée par état : Allumé, Éteint, ou Non défini.', max_length=20, verbose_name="Consigne d'état du chauffage")),
                ('radiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='actuators.radiator', verbose_name='Radiateur')),
                ('temperature_sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensors.temperaturesensor', verbose_name='Capteur de température')),
            ],
            options={
                'verbose_name': 'Pièce',
                'verbose_name_plural': 'Pièces',
            },
        ),
    ]
