# Generated by Django 5.2.1 on 2025-11-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='current_setpoint',
            new_name='temperature_setpoint',
        ),
        migrations.RemoveField(
            model_name='room',
            name='current_on_off_state',
        ),
        migrations.AddField(
            model_name='room',
            name='requested_heating_state',
            field=models.CharField(choices=[('off', 'Éteint'), ('on', 'Allumé'), ('unknown', 'Non défini')], default='unknown', help_text='État souhaité du chauffage dans cette pièce.', max_length=20, verbose_name="Consigne d'état du chauffage"),
        ),
    ]
