# Generated by Django 5.2.1 on 2025-11-27 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0002_rename_current_setpoint_room_temperature_setpoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatingPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots', models.JSONField(help_text='Une période non définie donnera forcément un chauffage éteint<br>Tous les créneaux doivent avoir le même type : temp ou onoff<br>Si "temp", "value" doit être numérique, exemple:<br>&nbsp;&nbsp;&nbsp;&nbsp;[{"start": "07:00", "end": "09:00", "type": "temp", "value": 20.0},{"start": "12:00", "end": "14:30", "type": "temp", "value": 24.0}]<br>Si "onoff"; "value" doit être "on" ou "off", exemple:<br>&nbsp;&nbsp;&nbsp;&nbsp;[{"start": "07:00", "end": "09:00", "type": "onoff", "value": "on"},{"start": "12:00", "end": "14:30", "type": "onoff", "value": "on"}]', verbose_name='Créneaux horaires')),
                ('slots_hash', models.CharField(db_index=True, help_text='Hash MD5 des créneaux pour déduplication', max_length=32, unique=True, verbose_name='Hash des créneaux')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pattern de chauffage',
                'verbose_name_plural': 'Patterns de chauffage',
            },
        ),
        migrations.CreateModel(
            name='RoomHeatingDayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heating_pattern', models.ForeignKey(help_text='Programme de chauffage appliqué pour cette journée', on_delete=django.db.models.deletion.PROTECT, related_name='day_plans', to='heating.heatingpattern', verbose_name='Pattern de chauffage')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heating_day_plans', to='rooms.room', verbose_name='Pièce')),
            ],
            options={
                'verbose_name': 'Plan de chauffage journalier',
                'verbose_name_plural': 'Plans de chauffage journaliers',
                'ordering': ['date', 'room'],
                'unique_together': {('room', 'date')},
            },
        ),
    ]
