# Generated by Django 5.2.1 on 2026-09-05 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0001_initial'),
        ('rooms', '0002_rename_current_setpoint_room_temperature_setpoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomHeatingDayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heating_pattern', models.ForeignKey(help_text='Programme de chauffage appliqué pour cette journée', on_delete=django.db.models.deletion.PROTECT, related_name='day_plans', to='planning.schedulepattern', verbose_name='Pattern de chauffage')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heating_day_plans', to='rooms.room', verbose_name='Pièce')),
            ],
            options={
                'verbose_name': 'Plan de chauffage journalier',
                'verbose_name_plural': 'Plans de chauffage journaliers',
                'ordering': ['date', 'room'],
                'unique_together': {('room', 'date')},
            },
        ),
    ]
