# Generated by Django 5.2.1 on 2025-11-23 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0002_rename_current_setpoint_room_temperature_setpoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatingPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots', models.JSONField(help_text='Liste des créneaux avec horaires et consignes', verbose_name='Créneaux horaires')),
                ('slots_hash', models.CharField(db_index=True, help_text='Hash MD5 des créneaux pour déduplication', max_length=32, unique=True, verbose_name='Hash des créneaux')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pattern de chauffage',
                'verbose_name_plural': 'Patterns de chauffage',
            },
        ),
        migrations.CreateModel(
            name='RoomHeatingDayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heating_pattern', models.ForeignKey(help_text='Programme de chauffage appliqué pour cette journée', on_delete=django.db.models.deletion.PROTECT, related_name='day_plans', to='heating.heatingpattern', verbose_name='Pattern de chauffage')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heating_day_plans', to='rooms.room', verbose_name='Pièce')),
            ],
            options={
                'verbose_name': 'Plan de chauffage journalier',
                'verbose_name_plural': 'Plans de chauffage journaliers',
                'ordering': ['date', 'room'],
                'unique_together': {('room', 'date')},
            },
        ),
    ]
