# Generated by Django 5.2.1 on 2026-09-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots', models.JSONField(help_text='Une période non définie donnera forcément un état éteint<br>Tous les créneaux doivent avoir le même type : temp ou onoff<br>Si "temp", "value" doit être numérique, exemple:<br>&nbsp;&nbsp;&nbsp;&nbsp;[{"start": "07:00", "end": "09:00", "type": "temp", "value": 20.0},{"start": "12:00", "end": "14:30", "type": "temp", "value": 24.0}]<br>Si "onoff"; "value" doit être "on" ou "off", exemple:<br>&nbsp;&nbsp;&nbsp;&nbsp;[{"start": "07:00", "end": "09:00", "type": "onoff", "value": "on"},{"start": "12:00", "end": "14:30", "type": "onoff", "value": "on"}]', verbose_name='Créneaux horaires')),
                ('slots_hash', models.CharField(db_index=True, help_text='Hash MD5 des créneaux pour déduplication', max_length=32, unique=True, verbose_name='Hash des créneaux')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pattern de planification',
                'verbose_name_plural': 'Patterns de planification',
            },
        ),
    ]
