# Generated by Django 5.2.1 on 2026-08-05 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actuators', '0002_shelly'),
    ]

    operations = [
        migrations.CreateModel(
            name='PulseSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('IN_PROGRESS', 'In progress')], default='IDLE', help_text='Verrou applicatif contre les déclenchements concurrents.', max_length=20, verbose_name='Statut')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernier déclenchement')),
                ('shelly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='actuators.shelly', verbose_name='Shelly')),
            ],
            options={
                'verbose_name': 'Interrupteur à impulsion',
                'verbose_name_plural': 'Interrupteurs à impulsion',
            },
        ),
    ]
