# Generated by Django 5.2.1 on 2026-08-11 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actuators', '0002_singlebuttonmotor'),
        ('sensors', '0004_doorcontactsensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarageDoor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('door_sensor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='garage_door', to='sensors.doorcontactsensor', verbose_name='Capteur')),
                ('motor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='garage_door', to='actuators.singlebuttonmotor', verbose_name='Moteur')),
            ],
            options={
                'verbose_name': 'Porte de garage',
                'verbose_name_plural': 'Portes de garage',
            },
        ),
    ]
