# Generated by Django 5.2.1 on 2026-09-03 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actuators', '0003_onoffswitch'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterHeater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('switch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='water_heater', to='actuators.onoffswitch', verbose_name='Interrupteur')),
            ],
            options={
                'verbose_name': 'Chauffe-eau',
                'verbose_name_plural': 'Chauffe-eau',
            },
        ),
    ]
