# Generated by Django 5.2.1 on 2026-09-05 13:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_waterheater'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterheater',
            name='actual_state',
            field=models.CharField(choices=[('OFF', 'Éteint'), ('ON', 'Allumé'), ('UNDEFINED', 'Indéterminé')], default='UNDEFINED', help_text='État réel du chauffe-eau selon le hardware', max_length=20, verbose_name='État réel'),
        ),
        migrations.AddField(
            model_name='waterheater',
            name='error',
            field=models.TextField(blank=True, help_text="Message d'erreur en cas de problème de communication hardware", null=True, verbose_name='Erreur'),
        ),
        migrations.AddField(
            model_name='waterheater',
            name='last_requested',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Horodatage de la dernière modification de requested_state', verbose_name='Dernière demande'),
        ),
        migrations.AddField(
            model_name='waterheater',
            name='requested_state',
            field=models.CharField(choices=[('OFF', 'Éteint'), ('ON', 'Allumé'), ('LOAD_SHED', 'Délestage (Éteint)')], default='OFF', help_text='État souhaité par le système', max_length=20, verbose_name='État demandé'),
        ),
    ]
