# Generated by Django 5.2.1 on 2026-09-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_waterheater_actual_state_waterheater_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterheater',
            name='power',
            field=models.PositiveIntegerField(default=3000, help_text='Puissance de la résistance, utilisée pour le calcul de puissance disponible lors du délestage', verbose_name='Puissance (W)'),
            preserve_default=False,
        ),
    ]
