# Generated by Django 5.2.1 on 2026-09-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_waterheater_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterheater',
            name='importance',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Critique'), (1, 'Haute'), (2, 'Moyenne'), (3, 'Basse')], default=0, help_text="Détermine l'ordre de délestage/rallumage face aux autres équipements (même échelle) — chauffe-eau traité critique par défaut : délesté en dernier, rallumé en premier", verbose_name='Importance'),
        ),
    ]
