MOCKED_ROOMS_DATA_FOR_API = [
    {
        "id": 1,
        "name": "Salon TV",
        "heating_control_mode": "thermostat",
        "current_setpoint": "21.5",
        "current_on_off_state": "unknown",
        "radiator__id": 2,
        "radiator__requested_state": "OFF",
        "radiator__actual_state": "OFF",
        "temperature_sensor__id": 1,
        "temperature_sensor__mac_address": "38:1F:8D:65:E9:1C",
    },
    {
        "id": 2,
        "name": "Salon Bureau",
        "heating_control_mode": "on_off",
        "current_setpoint": None,
        "current_on_off_state": "on",
        "radiator__id": 7,
        "radiator__requested_state": "OFF",
        "radiator__actual_state": "ON",
        "temperature_sensor__id": 2,
        "temperature_sensor__mac_address": "38:1F:8D:B2:1F:44",
    },
    {
        "id": 3,
        "name": "Cuisine",
        "heating_control_mode": "on_off",
        "current_setpoint": None,
        "current_on_off_state": "off",
        "radiator__id": 3,
        "radiator__requested_state": "ON",
        "radiator__actual_state": "OFF",
        "temperature_sensor__id": 3,
        "temperature_sensor__mac_address": "A4:C1:38:46:C0:F4",
    },
    {
        "id": 4,
        "name": "Salle de Bain",
        "heating_control_mode": "on_off",
        "current_setpoint": None,
        "current_on_off_state": "off",
        "radiator__id": 1,
        "radiator__requested_state": "OFF",
        "radiator__actual_state": "OFF",
        "temperature_sensor__id": 4,
        "temperature_sensor__mac_address": "A4:C1:38:66:A7:5E",
    },
    {
        "id": 5,
        "name": "Extérieur",
        "heating_control_mode": "on_off",
        "current_setpoint": None,
        "current_on_off_state": "on",
        "radiator__id": None,
        "radiator__requested_state": None,
        "radiator__actual_state": None,
        "temperature_sensor__id": 5,
        "temperature_sensor__mac_address": "A4:C1:38:4C:64:60",
    },
    {
        "id": 6,
        "name": "Couloir RDC",
        "heating_control_mode": "on_off",
        "current_setpoint": None,
        "current_on_off_state": "off",
        "radiator__id": 4,
        "radiator__requested_state": "LOAD_SHED",
        "radiator__actual_state": "OFF",
        "temperature_sensor__id": None,
        "temperature_sensor__mac_address": None,
    },
    {
        "id": 7,
        "name": "Chambre d'amis",
        "heating_control_mode": "on_off",
        "current_setpoint": None,
        "current_on_off_state": "off",
        "radiator__id": 5,
        "radiator__requested_state": "LOAD_SHED",
        "radiator__actual_state": "ON",
        "temperature_sensor__id": None,
        "temperature_sensor__mac_address": None,
    },
    {
        "id": 8,
        "name": "Chambre R",
        "heating_control_mode": "on_off",
        "current_setpoint": None,
        "current_on_off_state": "off",
        "radiator__id": 9,
        "radiator__requested_state": "ON",
        "radiator__actual_state": "ON",
        "temperature_sensor__id": None,
        "temperature_sensor__mac_address": None,
    },
    {
        "id": 9,
        "name": "Chambre MV",
        "heating_control_mode": "on_off",
        "current_setpoint": None,
        "current_on_off_state": "off",
        "radiator__id": 10,
        "radiator__requested_state": "OFF",
        "radiator__actual_state": "OFF",
        "temperature_sensor__id": None,
        "temperature_sensor__mac_address": None,
    },
    {
        "id": 10,
        "name": "Chambre M",
        "heating_control_mode": "on_off",
        "current_setpoint": None,
        "current_on_off_state": "off",
        "radiator__id": 12,
        "radiator__requested_state": "OFF",
        "radiator__actual_state": "OFF",
        "temperature_sensor__id": None,
        "temperature_sensor__mac_address": None,
    },
]

ENRICHED_ROOM_DATA_FOR_API = [
    {
        "id": 1,
        "name": "Salon TV",
        "heating_control_mode": "on_off",
        "current_setpoint": None,
        "current_on_off_state": "off",
        "radiator__id": 2,
        "radiator__requested_state": "OFF",
        "radiator__actual_state": "OFF",
        "temperature_sensor__id": 1,
        "temperature_sensor__mac_address": "38:1F:8D:65:E9:1C",
        "temperature_sensor__rssi": -87,
        "temperature_sensor__current_temperature": 20.69,
        "temperature_sensor__current_dt": "2025-10-15T12:59:32.465Z",
        "temperature_sensor__previous_temperature": 20.68,
        "temperature_sensor__previous_dt": "2025-10-15T12:58:37.566Z",
    },
    {
        "id": 2,
        "name": "Salon Bureau",
        "heating_control_mode": "on_off",
        "current_setpoint": None,
        "current_on_off_state": "off",
        "radiator__id": 7,
        "radiator__requested_state": "OFF",
        "radiator__actual_state": "OFF",
        "temperature_sensor__id": 2,
        "temperature_sensor__mac_address": "38:1F:8D:B2:1F:44",
        "temperature_sensor__rssi": -85,
        "temperature_sensor__current_temperature": 21.94,
        "temperature_sensor__current_dt": "2025-10-15T12:59:22.745Z",
        "temperature_sensor__previous_temperature": 21.95,
        "temperature_sensor__previous_dt": "2025-10-15T12:58:32.855Z",
    },
    {
        "id": 3,
        "name": "Cuisine",
        "heating_control_mode": "on_off",
        "current_setpoint": None,
        "current_on_off_state": "off",
        "radiator__id": 3,
        "radiator__requested_state": "OFF",
        "radiator__actual_state": "OFF",
        "temperature_sensor__id": 3,
        "temperature_sensor__mac_address": "A4:C1:38:46:C0:F4",
        "temperature_sensor__rssi": -81,
        "temperature_sensor__current_temperature": 20.2,
        "temperature_sensor__current_dt": "2025-10-15T12:59:36.876Z",
        "temperature_sensor__previous_temperature": 20.17,
        "temperature_sensor__previous_dt": "2025-10-15T12:58:36.977Z",
    },
    {
        "id": 4,
        "name": "Salle de Bain",
        "heating_control_mode": "on_off",
        "current_setpoint": None,
        "current_on_off_state": "off",
        "radiator__id": 1,
        "radiator__requested_state": "OFF",
        "radiator__actual_state": "OFF",
        "temperature_sensor__id": 4,
        "temperature_sensor__mac_address": "A4:C1:38:66:A7:5E",
        "temperature_sensor__rssi": -58,
        "temperature_sensor__current_temperature": 20.490000000000002,
        "temperature_sensor__current_dt": "2025-10-15T12:59:37.281Z",
        "temperature_sensor__previous_temperature": 20.54,
        "temperature_sensor__previous_dt": "2025-10-15T12:58:37.297Z",
    },
    {
        "id": 5,
        "name": "Extérieur",
        "heating_control_mode": "on_off",
        "current_setpoint": None,
        "current_on_off_state": "unknown",
        "radiator__id": None,
        "radiator__requested_state": None,
        "radiator__actual_state": None,
        "temperature_sensor__id": 5,
        "temperature_sensor__mac_address": "A4:C1:38:4C:64:60",
        "temperature_sensor__rssi": -64,
        "temperature_sensor__current_temperature": 15.870000000000001,
        "temperature_sensor__current_dt": "2025-10-15T12:59:40.427Z",
        "temperature_sensor__previous_temperature": 15.83,
        "temperature_sensor__previous_dt": "2025-10-15T12:58:40.400Z",
    },
    {
        "id": 6,
        "name": "Couloir RDC",
        "heating_control_mode": "on_off",
        "current_setpoint": None,
        "current_on_off_state": "off",
        "radiator__id": 4,
        "radiator__requested_state": "OFF",
        "radiator__actual_state": "OFF",
        "temperature_sensor__id": None,
        "temperature_sensor__mac_address": None,
        "temperature_sensor__rssi": None,
        "temperature_sensor__current_temperature": None,
        "temperature_sensor__current_dt": None,
        "temperature_sensor__previous_temperature": None,
        "temperature_sensor__previous_dt": None,
    },
    {
        "id": 7,
        "name": "Chambre d'amis",
        "heating_control_mode": "on_off",
        "current_setpoint": None,
        "current_on_off_state": "off",
        "radiator__id": 5,
        "radiator__requested_state": "OFF",
        "radiator__actual_state": "OFF",
        "temperature_sensor__id": None,
        "temperature_sensor__mac_address": None,
        "temperature_sensor__rssi": None,
        "temperature_sensor__current_temperature": None,
        "temperature_sensor__current_dt": None,
        "temperature_sensor__previous_temperature": None,
        "temperature_sensor__previous_dt": None,
    },
    {
        "id": 8,
        "name": "Chambre R",
        "heating_control_mode": "on_off",
        "current_setpoint": None,
        "current_on_off_state": "off",
        "radiator__id": 9,
        "radiator__requested_state": "OFF",
        "radiator__actual_state": "OFF",
        "temperature_sensor__id": None,
        "temperature_sensor__mac_address": None,
        "temperature_sensor__rssi": None,
        "temperature_sensor__current_temperature": None,
        "temperature_sensor__current_dt": None,
        "temperature_sensor__previous_temperature": None,
        "temperature_sensor__previous_dt": None,
    },
    {
        "id": 9,
        "name": "Chambre MV",
        "heating_control_mode": "on_off",
        "current_setpoint": None,
        "current_on_off_state": "off",
        "radiator__id": 10,
        "radiator__requested_state": "OFF",
        "radiator__actual_state": "OFF",
        "temperature_sensor__id": None,
        "temperature_sensor__mac_address": None,
        "temperature_sensor__rssi": None,
        "temperature_sensor__current_temperature": None,
        "temperature_sensor__current_dt": None,
        "temperature_sensor__previous_temperature": None,
        "temperature_sensor__previous_dt": None,
    },
    {
        "id": 10,
        "name": "Chambre M",
        "heating_control_mode": "on_off",
        "current_setpoint": None,
        "current_on_off_state": "off",
        "radiator__id": 12,
        "radiator__requested_state": "OFF",
        "radiator__actual_state": "OFF",
        "temperature_sensor__id": None,
        "temperature_sensor__mac_address": None,
        "temperature_sensor__rssi": None,
        "temperature_sensor__current_temperature": None,
        "temperature_sensor__current_dt": None,
        "temperature_sensor__previous_temperature": None,
        "temperature_sensor__previous_dt": None,
    },
]
