# Generated by Django 3.2.2 on 2021-05-24 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0002_alter_room_heating_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adress', models.IntegerField(unique=True)),
                ('last_measured_temperature', models.DecimalField(decimal_places=1, default=99.9, max_digits=3)),
                ('previous_measured_temperature', models.DecimalField(decimal_places=1, default=99.9, max_digits=3)),
                ('associated_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
    ]
