# Generated by Django 5.0 on 2024-12-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturehumiditysensor',
            name='rssi',
            field=models.IntegerField(blank=True, help_text='Puissance du signal RSSI mesurée en dBm', null=True),
        ),
    ]
