# Generated by Django 3.2.2 on 2021-05-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_alter_temperaturesensor_associated_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperaturesensor',
            old_name='adress',
            new_name='address',
        ),
    ]
