# Generated by Django 3.2.2 on 2021-05-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_rename_adress_temperaturesensor_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperaturesensor',
            name='address',
        ),
        migrations.AddField(
            model_name='temperaturesensor',
            name='sensor_folder_path',
            field=models.CharField(default=123456, max_length=100),
            preserve_default=False,
        ),
    ]
