# Generated by Django 3.2.2 on 2021-05-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_auto_20210524_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturesensor',
            name='name',
            field=models.CharField(default='unnamed', max_length=100),
        ),
        migrations.AlterField(
            model_name='temperaturesensor',
            name='sensor_folder_path',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
