# Generated by Django 3.2.2 on 2021-05-24 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_auto_20210524_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperaturesensor',
            name='last_measured_temperature',
        ),
        migrations.RemoveField(
            model_name='temperaturesensor',
            name='previous_measured_temperature',
        ),
        migrations.CreateModel(
            name='TemperatureHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=1, default=99.9, max_digits=3)),
                ('associated_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.temperaturesensor')),
            ],
        ),
    ]
