# Generated by Django 3.2.2 on 2021-05-24 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_auto_20210524_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturehistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
