# Generated by Django 3.2.2 on 2021-05-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0008_temperaturehistory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturehistory',
            name='temperature',
            field=models.IntegerField(),
        ),
    ]
