# Generated by Django 3.2.2 on 2021-05-24 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0009_alter_temperaturehistory_temperature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperaturehistory',
            old_name='date',
            new_name='date_time',
        ),
    ]
