# Generated by Django 5.2.1 on 2025-10-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('logged_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-logged_at'],
                'constraints': [models.UniqueConstraint(fields=('service', 'logged_at', 'level', 'message'), name='unique_system_log')],
            },
        ),
    ]
