export const DEFAULT_VOLTAGE = 230;

export const PTEC_LABELS = {
  "TH..": "Base",
  "HC..": "Heures Creuses",
  "HP..": "Heures Pleines",
  "HN..": "Heures Normales",
  "PM..": "Pointe Mobile",
  HCJB: "Heures Creuses Jour Bleu",
  HCJW: "Heures Creuses Jour Blanc",
  HCJR: "Heures Creuses Jour Rouge",
  HPJB: "Heures Pleines Jour Bleu",
  HPJW: "Heures Pleines Jour Blanc",
  HPJR: "Heures Pleines Jour Rouge",
  DEFAULT: "Inconnu",
};

export const TELEINFO_LABELS = {
  ADCO: "Identifiant du compteur",
  OPTARIF: "Option tarifaire",
  ISOUSC: "Intensité souscrite",
  BASE: "Index option Base",
  HCHC: "Index Heures Creuses",
  HCHP: "	Index Heures Pleines",
  EJPHN: "Index EJP Heures Normales",
  EJPHPM: "Index EJP Heures de Pointe Mobile",
  BBRHCJB: "Index Tempo Heures Creuses Jours Bleus",
  BBRHPJB: "Index Tempo Heures Pleines Jours Bleus",
  BBRHCJW: "Index Tempo Heures Creuses Jours Blancs",
  BBRHPJW: "Index Tempo Heures Pleines Jours Blancs",
  BBRHCJR: "Index Tempo Heures Creuses Jours Rouges",
  BBRHPJR: "Index Tempo Heures Pleines Jours Rouges",
  PEJP: "Préavis début EJP",
  PTEC: "Période tarifaire en cours",
  DEMAIN: "Couleur du lendemain",
  IINST: "Intensité instantanée",
  IMAX: "Intensité maximale atteinte",
  ADPS: "Avertissement dépassement puissance souscrite",
  MOTDETAT: "Mot d'état du compteur",
  HHPHC: "Horaire HP/HC",
  PAPP: "Puissance apparente instantanée",
  PMAX: "Puissance maximale triphasée",
};

export const INDEX_LABELS = {
  BASE: "Consommation",
  HCHC: "Heures Creuses",
  HCHP: "Heures Pleines",
  EJPHN: "Heures Normales",
  EJPHPM: "Heures de Pointe Mobile",
  BBRHCJB: "Heures Creuses Jours Bleus",
  BBRHPJB: "Heures Pleines Jours Bleus",
  BBRHCJW: "Heures Creuses Jours Blancs",
  BBRHPJW: "Heures Pleines Jours Blancs",
  BBRHCJR: "Heures Creuses Jours Rouges",
  BBRHPJR: "Heures Pleines Jours Rouges",
  missing_indexes: "Extrapolées",
};

export const TELEINFO_UNITS = {
  ISOUSC: "A",
  IINST: "A",
  IMAX: "A",
  PAPP: "VA",
  PMAX: "VA",
  BASE: "Wh",
  HCHC: "Wh",
  HCHP: "Wh",
  EJPHN: "Wh",
  EJPHPM: "Wh",
  BBRHCJB: "Wh",
  BBRHPJB: "Wh",
  BBRHCJW: "Wh",
  BBRHPJW: "Wh",
  BBRHCJR: "Wh",
  BBRHPJR: "Wh",
};

export const OPTARIF_LABELS = {
  BASE: "Base",
  "HC..": "Heures Pleines/Creuses",
  "EJP.": "Effacement Jour de Pointe",
  BBRx: "Tempo",
  DEFAULT: "Option inconnue",
};
