# Generated by Django 5.0 on 2024-12-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_heating_without_teleinfo', models.BooleanField(default=False, help_text="Autoriser l'allumage des radiateurs même si les données de téléinfo ne sont pas disponibles")),
            ],
        ),
    ]
