# Generated by Django 5.2.1 on 2025-10-07 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temperaturesensor',
            options={'verbose_name': 'Capteur de température', 'verbose_name_plural': 'Capteurs de température'},
        ),
    ]
