# Generated by Django 5.2.1 on 2025-10-07 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_alter_temperaturesensor_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperaturesensor',
            old_name='nom',
            new_name='name',
        ),
    ]
