# Generated by Django 5.2.1 on 2026-08-11 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
        ('sensors', '0003_rename_nom_temperaturesensor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoorContactSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('closed_when_true', models.BooleanField(default=True, help_text="Coché si la porte est fermée quand l'état brut du capteur est vrai (décoché si c'est l'inverse)", verbose_name='Fermée quand vrai')),
                ('sensor_true_false', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='door_contact_sensor', to='device.sensortruefalse', verbose_name='Capteur')),
            ],
            options={
                'verbose_name': 'Capteur de porte',
                'verbose_name_plural': 'Capteurs de porte',
            },
        ),
    ]
