# Generated by Django 5.0 on 2024-12-03 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('radiators', '0002_radiator_error'),
        ('sensors', '0002_alter_temperaturehumiditysensor_rssi'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('target_temperature', models.FloatField(blank=True, null=True)),
                ('heating_mode', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automatic'), ('off', 'Off')], default='off', max_length=10)),
                ('radiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='radiators.radiator')),
                ('temperature_humidity_sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensors.temperaturehumiditysensor')),
            ],
        ),
    ]
