# Generated by Django 5.0 on 2024-11-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiator',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
