# Generated by Django 5.2.1 on 2025-10-03 18:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Radiator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du radiateur', max_length=100, unique=True, verbose_name='Nom')),
                ('power', models.PositiveIntegerField(help_text='Puissance électrique du radiateur en watts', verbose_name='Puissance (W)')),
                ('control_pin', models.PositiveSmallIntegerField(choices=[(0, 'Pin 0'), (1, 'Pin 1'), (2, 'Pin 2'), (3, 'Pin 3'), (4, 'Pin 4'), (5, 'Pin 5'), (6, 'Pin 6'), (7, 'Pin 7'), (8, 'Pin 8'), (9, 'Pin 9'), (10, 'Pin 10'), (11, 'Pin 11'), (12, 'Pin 12'), (13, 'Pin 13'), (14, 'Pin 14'), (15, 'Pin 15')], help_text='Pin du MCP23017 contrôlant ce radiateur (0-15)', unique=True, verbose_name='Pin MCP23017')),
                ('importance', models.PositiveSmallIntegerField(choices=[(0, 'Critique'), (1, 'Haute'), (2, 'Moyenne'), (3, 'Basse')], default=2, help_text="Détermine l'ordre de délestage (critique = coupé en dernier)", verbose_name='Importance du chauffage')),
                ('requested_state', models.CharField(choices=[('OFF', 'Éteint'), ('ON', 'Allumé'), ('LOAD_SHED', 'Délestage (Éteint)')], default='OFF', help_text='État souhaité par le système', max_length=20, verbose_name='État demandé')),
                ('actual_state', models.CharField(choices=[('OFF', 'Éteint'), ('ON', 'Allumé'), ('UNDEFINED', 'Indéterminé')], default='UNDEFINED', help_text='État réel du radiateur selon le hardware', max_length=20, verbose_name='État réel')),
                ('last_requested', models.DateTimeField(default=django.utils.timezone.now, help_text='Horodatage de la dernière modification de requested_state', verbose_name='Dernière demande')),
                ('error', models.TextField(blank=True, help_text="Message d'erreur en cas de problème de communication hardware", null=True, verbose_name='Erreur')),
            ],
            options={
                'verbose_name': 'Radiateur',
                'verbose_name_plural': 'Radiateurs',
            },
        ),
    ]
