# Generated by Django 5.2.1 on 2026-08-11 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actuators', '0001_initial'),
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleButtonMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('pulse_seconds', models.FloatField(default=1, help_text="Durée d'activation du relais avant relâchement automatique", verbose_name='Durée du pulse (s)')),
                ('relay_on_off', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='single_button_motor', to='device.relayonoff', verbose_name='Relais')),
            ],
            options={
                'verbose_name': 'Moteur bouton unique',
                'verbose_name_plural': 'Moteurs bouton unique',
            },
        ),
    ]
