# Generated by Django 5.2.1 on 2025-10-18 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actuators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiator',
            name='last_requested',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 18, 22, 24, 58, 414357, tzinfo=datetime.timezone.utc), help_text='Horodatage de la dernière modification de requested_state', verbose_name='Dernière demande'),
        ),
    ]
