# Generated by Django 5.2.1 on 2026-08-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actuators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du Shelly', max_length=100, unique=True, verbose_name='Nom')),
                ('reference', models.CharField(choices=[('SHELLY_1_MINI_GEN3', 'Shelly 1 Mini Gen3')], default='SHELLY_1_MINI_GEN3', help_text='Référence exacte du Shelly (détermine le comportement du driver)', max_length=30, verbose_name='Référence')),
                ('ip', models.GenericIPAddressField(help_text='Adresse IP locale du Shelly (réservée sur la box)', protocol='IPv4', unique=True, verbose_name='Adresse IP')),
            ],
            options={
                'verbose_name': 'Shelly',
                'verbose_name_plural': 'Shelly',
            },
        ),
    ]
