# Generated by Django 5.2.1 on 2026-09-03 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actuators', '0002_singlebuttonmotor'),
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnOffSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('relay_on_off', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='on_off_switch', to='device.relayonoff', verbose_name='Relais')),
            ],
            options={
                'verbose_name': 'Interrupteur on/off',
                'verbose_name_plural': 'Interrupteurs on/off',
            },
        ),
    ]
