# Generated by Django 5.2.1 on 2026-08-08 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(choices=[('SHELLY_1_MINI_GEN3', 'SHELLY_1_MINI_GEN3')], help_text='Modèle exact du device (détermine ses IO et son driver)', max_length=30, verbose_name='Référence')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='IPDevice',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='device.device')),
                ('ip', models.GenericIPAddressField(help_text='Adresse IP locale du device (réservée sur la box)', protocol='IPv4', unique=True, verbose_name='Adresse IP')),
            ],
            options={
                'verbose_name': 'Device IP',
                'verbose_name_plural': 'Devices IP',
            },
            bases=('device.device',),
        ),
        migrations.CreateModel(
            name='DeviceIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Identifiant stable de l'IO, tel que déclaré dans le modèle du device", max_length=50, verbose_name='Clé')),
                ('name', models.CharField(help_text='Copié depuis la déclaration du modèle à la création du device', max_length=100, verbose_name='Nom')),
                ('mode', models.CharField(choices=[('relay_on_off', 'Relais on/off'), ('sensor_true_false', 'Capteur (vrai/faux)'), ('not_used_in_app', "Non utilisée dans l'app")], default='not_used_in_app', help_text="Configuration actuelle de cette IO. Les choix affichés dans l'admin sont restreints à ceux compatibles avec le type de cette IO — voir device.catalog.IO_TYPE_ALLOWED_MODES.", max_length=30, verbose_name='Mode')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='io', to='device.device', verbose_name='Device')),
            ],
            options={
                'verbose_name': 'IO',
                'verbose_name_plural': 'IO',
            },
        ),
        migrations.CreateModel(
            name='RelayOnOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_io', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relay_on_off', to='device.deviceio', verbose_name='IO')),
            ],
            options={
                'verbose_name': 'Relais on/off',
                'verbose_name_plural': 'Relais on/off',
            },
        ),
        migrations.CreateModel(
            name='SensorTrueFalse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_io', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_true_false', to='device.deviceio', verbose_name='IO')),
            ],
            options={
                'verbose_name': 'Capteur (vrai/faux)',
                'verbose_name_plural': 'Capteurs (vrai/faux)',
            },
        ),
        migrations.AddConstraint(
            model_name='deviceio',
            constraint=models.UniqueConstraint(fields=('device', 'key'), name='unique_device_io_key'),
        ),
    ]
