# Generated by Django 5.2.1 on 2025-06-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyindexes',
            name='tarif_periods',
            field=models.JSONField(default=dict),
        ),
    ]
