# Generated by Django 5.2.1 on 2025-06-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0002_dailyindexes_tarif_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyindexes',
            name='subscribed_power',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
