# Generated by Django 3.2.2 on 2021-05-24 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0002_alter_room_heating_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('maximum_power_consumption', models.IntegerField()),
                ('control_pin', models.IntegerField()),
                ('is_on', models.BooleanField(default=False)),
                ('associated_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.room')),
            ],
        ),
    ]
