# Generated by Django 3.2.2 on 2021-05-24 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_heating_priority'),
        ('heaters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heater',
            name='associated_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.room'),
        ),
    ]
