# Generated by Django 3.2.2 on 2021-05-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heaters', '0002_alter_heater_associated_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heater',
            name='control_pin',
            field=models.IntegerField(unique=True),
        ),
    ]
