# Generated by Django 5.2.1 on 2026-09-05 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("equipment", "0002_waterheater"),
        ("planning", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaterHeaterDayPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schedule_pattern",
                    models.ForeignKey(
                        help_text="Programme appliqué pour cette journée",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="water_heater_day_plans",
                        to="planning.schedulepattern",
                        verbose_name="Pattern de planification",
                    ),
                ),
                (
                    "water_heater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_plans",
                        to="equipment.waterheater",
                        verbose_name="Chauffe-eau",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan de chauffe-eau journalier",
                "verbose_name_plural": "Plans de chauffe-eau journaliers",
                "ordering": ["date", "water_heater"],
                "unique_together": {("water_heater", "date")},
            },
        ),
    ]
