# Generated by Django 5.2.1 on 2026-09-27 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_waterheater_importance'),
        ('planning', '0001_initial'),
        ('water_heater', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waterheaterdayplan',
            options={'ordering': ['date', 'equipment'], 'verbose_name': 'Plan de chauffe-eau journalier', 'verbose_name_plural': 'Plans de chauffe-eau journaliers'},
        ),
        migrations.RenameField(
            model_name='waterheaterdayplan',
            old_name='water_heater',
            new_name='equipment',
        ),
        migrations.AlterUniqueTogether(
            name='waterheaterdayplan',
            unique_together={('equipment', 'date')},
        ),
        migrations.AlterField(
            model_name='waterheaterdayplan',
            name='schedule_pattern',
            field=models.ForeignKey(help_text='Programme appliqué pour cette journée', on_delete=django.db.models.deletion.PROTECT, to='planning.schedulepattern', verbose_name='Pattern de planification'),
        ),
    ]
